// eslint-disable-next-line import/prefer-default-export
export const detailedInfo = {
  RecordLabel: "Granderson Properties, LLC",
  SystemOfRecord: "FIS",
  HeaderInfo: {
    ID: "7",
    BorrowerName: "Granderson Properties",
    RelationshipManager: "Buffy Jones",
  },
  TableHeaders: [
    {
      DataWarehouseSoid: "5f2cbf8ef85e4d7d54efe983",
      DataWarehouseName: "FIS",
      LocalId: "7",
    },
    {
      DataWarehouseSoid: "5f2cbf8ef85e4d7d54efe98c",
      DataWarehouseName: "Temenos",
      LocalId: "18",
    },
    {
      DataWarehouseSoid: "5f2cbf8ef85e4d7d54efe992",
      DataWarehouseName: "Salesforce",
      LocalId: "29",
    },
    {
      DataWarehouseSoid: "5f2cbf8ef85e4d7d54efe995",
      DataWarehouseName: "Data Warehouse",
      LocalId: "40",
    },
  ],
  Fields: [
    {
      FieldName: "RelationshipName",
      Label: "Relationship Name",
      Records: [
        {
          Soid: "5f2cbf8ef85e4d7d54efea14",
          Value: "Granderson Properties, LLC",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea35",
          Value: "Granderson Properties, LLC",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea56",
          Value: "Granderson Properties, LLC.",
          Diff: true,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea77",
          Value: "Granderson Propertees, LLC",
          Diff: true,
          ChangeRequest: null,
        },
      ],
    },
    {
      FieldName: "BorrowerName",
      Label: "Borrower Name",
      Records: [
        {
          Soid: "5f2cbf8ef85e4d7d54efea14",
          Value: "Granderson Properties",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea35",
          Value: "Granderson Properties, LLC",
          Diff: true,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea56",
          Value: "Granderson Properties, INC",
          Diff: true,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea77",
          Value: "Granderson Propertees",
          Diff: true,
          ChangeRequest: null,
        },
      ],
    },
    {
      FieldName: "DepositorName",
      Label: "Depositor Name",
      Records: [
        {
          Soid: "5f2cbf8ef85e4d7d54efea14",
          Value: "Granderson Properties, LLC",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea35",
          Value: "Granderson Properties,",
          Diff: true,
          ChangeRequest: {
            CompanySoid: null,
            BusinessEntity: "Entity",
            WarehouseSoid: null,
            WarehouseName: "Temenos",
            LocalId: "18",
            ReferenceLocalId: null,
            FieldReference: null,
            FieldName: "DepositorName",
            FieldValue: "Granderson Properties,",
            FixedValue: "Granderson Properties, LLC",
            Status: "Rejected",
            RequestedBy: "Taharka",
            RequestedId: "5f285555f85e4dc5245b344b",
            RequestedOn: null,
            ApproverName: "Neil Kjeldsen",
            ApproverSoid: "5f285555f85e4dc5245b344e",
            Start: null,
            End: null,
            ApprovalsCount: 0,
            Soid: "5f28f279f85e4dcd0c0c1521",
            SqlId: 0,
            CreatedOn: "0001-01-01T00:00:00",
            CreatedID: null,
            CreatedBy: null,
            CreatedAt: null,
            LastSavedOn: "0001-01-01T00:00:00",
          },
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea56",
          Value: "Granderson Properties,",
          Diff: true,
          ChangeRequest: {
            CompanySoid: null,
            BusinessEntity: "Entity",
            WarehouseSoid: null,
            WarehouseName: "Salesforce",
            LocalId: "29",
            ReferenceLocalId: null,
            FieldReference: null,
            FieldName: "DepositorName",
            FieldValue: "Granderson Properties,",
            FixedValue: "Granderson Properties, LLC",
            Status: "In Progress",
            RequestedBy: "Taharka",
            RequestedId: "5f285555f85e4dc5245b344b",
            RequestedOn: null,
            ApproverName: "Neil Kjeldsen",
            ApproverSoid: "5f285555f85e4dc5245b344e",
            Start: null,
            End: null,
            ApprovalsCount: 0,
            Soid: "5f28f279f85e4dcd0c0c151e",
            SqlId: 0,
            CreatedOn: "0001-01-01T00:00:00",
            CreatedID: null,
            CreatedBy: null,
            CreatedAt: null,
            LastSavedOn: "0001-01-01T00:00:00",
          },
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea77",
          Value: "Granderson Propertees, LLC",
          Diff: true,
          ChangeRequest: {
            CompanySoid: null,
            BusinessEntity: "Entity",
            WarehouseSoid: null,
            WarehouseName: "Data Warehouse",
            LocalId: "40",
            ReferenceLocalId: null,
            FieldReference: null,
            FieldName: "DepositorName",
            FieldValue: "Granderson Propertees, LLC",
            FixedValue: "Granderson Properties, LLC",
            Status: "Approved",
            RequestedBy: "Taharka",
            RequestedId: "5f285555f85e4dc5245b344b",
            RequestedOn: null,
            ApproverName: "Neil Kjeldsen",
            ApproverSoid: "5f285555f85e4dc5245b344e",
            Start: null,
            End: null,
            ApprovalsCount: 0,
            Soid: "5f28f279f85e4dcd0c0c150d",
            SqlId: 0,
            CreatedOn: "0001-01-01T00:00:00",
            CreatedID: null,
            CreatedBy: null,
            CreatedAt: null,
            LastSavedOn: "0001-01-01T00:00:00",
          },
        },
      ],
    },
    {
      FieldName: "LegalName",
      Label: "Legal Name",
      Records: [
        {
          Soid: "5f2cbf8ef85e4d7d54efea14",
          Value: "Granderson Properties, LLC",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea35",
          Value: "Granderson Prop.",
          Diff: true,
          ChangeRequest: {
            CompanySoid: "5f2cbf8ef85e4d7d54efe9bc",
            BusinessEntity: "Entity",
            WarehouseSoid: "5f2cbf8ef85e4d7d54efe98c",
            WarehouseName: "Temenos",
            LocalId: "18",
            ReferenceLocalId: null,
            FieldReference: null,
            FieldName: "LegalName",
            FieldValue: "Granderson Prop.",
            FixedValue: "Granderson Property",
            Status: "New",
            RequestedBy: "Taharka",
            RequestedId: "5f2cbf8ef85e4d7d54efe9f6",
            RequestedOn: null,
            ApproverName: "Neil Kjeldsen",
            ApproverSoid: "5f2cbf8ef85e4d7d54efe9f9",
            Start: null,
            End: null,
            ApprovalsCount: 0,
            Soid: "5f36b58cf85e4dcd3c0c65c7",
            SqlId: 0,
            CreatedOn: "0001-01-01T00:00:00",
            CreatedID: null,
            CreatedBy: null,
            CreatedAt: null,
            LastSavedOn: "0001-01-01T00:00:00",
          },
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea56",
          Value: "Granderson Prop.",
          Diff: true,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea77",
          Value: "Granderson Properties, LLC",
          Diff: false,
          ChangeRequest: null,
        },
      ],
    },
    {
      FieldName: "Alias1",
      Label: "Alias",
      Records: [
        {
          Soid: "5f2cbf8ef85e4d7d54efea14",
          Value: "",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea35",
          Value: "",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea56",
          Value: "",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea77",
          Value: "",
          Diff: false,
          ChangeRequest: null,
        },
      ],
    },
    {
      FieldName: "HQAddressStreet",
      Label: "HQ Address Street",
      Records: [
        {
          Soid: "5f2cbf8ef85e4d7d54efea14",
          Value: "227 Davis Street",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea35",
          Value: "227 Davis Street",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea56",
          Value: "227 Davis Street",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea77",
          Value: "227 Davis Street",
          Diff: false,
          ChangeRequest: null,
        },
      ],
    },
    {
      FieldName: "HQAddressCity",
      Label: "HQ Address City",
      Records: [
        {
          Soid: "5f2cbf8ef85e4d7d54efea14",
          Value: "Claremont",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea35",
          Value: "Claremont",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea56",
          Value: "Claremont",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea77",
          Value: "Claremont",
          Diff: false,
          ChangeRequest: null,
        },
      ],
    },
    {
      FieldName: "HQAddressState",
      Label: "HQ Address State",
      Records: [
        {
          Soid: "5f2cbf8ef85e4d7d54efea14",
          Value: "CA",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea35",
          Value: "CA",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea56",
          Value: "CA",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea77",
          Value: "CA",
          Diff: false,
          ChangeRequest: null,
        },
      ],
    },
    {
      FieldName: "HQAddressPostalCode",
      Label: "HQ Address Postal Code",
      Records: [
        {
          Soid: "5f2cbf8ef85e4d7d54efea14",
          Value: "91711",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea35",
          Value: "91711",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea56",
          Value: "91711",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea77",
          Value: "91711",
          Diff: false,
          ChangeRequest: null,
        },
      ],
    },
    {
      FieldName: "MailingAddressStreet",
      Label: "Mailing Address Street",
      Records: [
        {
          Soid: "5f2cbf8ef85e4d7d54efea14",
          Value: "227 Davis Street",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea35",
          Value: "227 Davis Street",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea56",
          Value: "227 Davis Street",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea77",
          Value: "227 Davis Street",
          Diff: false,
          ChangeRequest: null,
        },
      ],
    },
    {
      FieldName: "MailingAddressCity",
      Label: "Mailing Address City",
      Records: [
        {
          Soid: "5f2cbf8ef85e4d7d54efea14",
          Value: "Claremont",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea35",
          Value: "Claremont",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea56",
          Value: "Claremont",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea77",
          Value: "Claremont",
          Diff: false,
          ChangeRequest: null,
        },
      ],
    },
    {
      FieldName: "MailingAddressState",
      Label: "Mailing Address State",
      Records: [
        {
          Soid: "5f2cbf8ef85e4d7d54efea14",
          Value: "CA",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea35",
          Value: "CA",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea56",
          Value: "CA",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea77",
          Value: "CA",
          Diff: false,
          ChangeRequest: null,
        },
      ],
    },
    {
      FieldName: "MailingAddressPostalCode",
      Label: "Mailing Address Postal Code",
      Records: [
        {
          Soid: "5f2cbf8ef85e4d7d54efea14",
          Value: "91711",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea35",
          Value: "91711",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea56",
          Value: "91711",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea77",
          Value: "91711",
          Diff: false,
          ChangeRequest: null,
        },
      ],
    },
    {
      FieldName: "Phone1",
      Label: "Phone 1",
      Records: [
        {
          Soid: "5f2cbf8ef85e4d7d54efea14",
          Value: "2139876123",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea35",
          Value: "2139876123",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea56",
          Value: "2139876123",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea77",
          Value: "2139876123",
          Diff: false,
          ChangeRequest: null,
        },
      ],
    },
    {
      FieldName: "Phone2",
      Label: "Phone 2",
      Records: [
        {
          Soid: "5f2cbf8ef85e4d7d54efea14",
          Value: "2139172134",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea35",
          Value: "2139172134",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea56",
          Value: "2139172134",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea77",
          Value: "2139172134",
          Diff: false,
          ChangeRequest: null,
        },
      ],
    },
    {
      FieldName: "PhoneType1",
      Label: "Phone 1 Type",
      Records: [
        {
          Soid: "5f2cbf8ef85e4d7d54efea14",
          Value: "Office",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea35",
          Value: "Office",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea56",
          Value: "Office",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea77",
          Value: "Office",
          Diff: false,
          ChangeRequest: null,
        },
      ],
    },
    {
      FieldName: "PhoneType2",
      Label: "Phone 2 Type",
      Records: [
        {
          Soid: "5f2cbf8ef85e4d7d54efea14",
          Value: "Mobile",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea35",
          Value: "Mobile",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea56",
          Value: "Mobile",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea77",
          Value: "Mobile",
          Diff: false,
          ChangeRequest: null,
        },
      ],
    },
    {
      FieldName: "EmailAddress1",
      Label: "Email Address 1",
      Records: [
        {
          Soid: "5f2cbf8ef85e4d7d54efea14",
          Value: "grandersonprop@gmail.com",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea35",
          Value: "grandersonprop@gmail.com",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea56",
          Value: "grandersonprop@gmail.com",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea77",
          Value: "grandersonprop@gmail.com",
          Diff: false,
          ChangeRequest: null,
        },
      ],
    },
    {
      FieldName: "EmailAddress2",
      Label: "Email Address 2",
      Records: [
        {
          Soid: "5f2cbf8ef85e4d7d54efea14",
          Value: "",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea35",
          Value: "",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea56",
          Value: "",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea77",
          Value: "",
          Diff: false,
          ChangeRequest: null,
        },
      ],
    },
    {
      FieldName: "EmailAddress3",
      Label: "Email Address 3",
      Records: [
        {
          Soid: "5f2cbf8ef85e4d7d54efea14",
          Value: "",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea35",
          Value: "",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea56",
          Value: "",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea77",
          Value: "",
          Diff: false,
          ChangeRequest: null,
        },
      ],
    },
    {
      FieldName: "Website",
      Label: "Website",
      Records: [
        {
          Soid: "5f2cbf8ef85e4d7d54efea14",
          Value: "grandersonprop.com",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea35",
          Value: "grandersonprop.com",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea56",
          Value: "grandersonprop.com",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea77",
          Value: "grandersonprop.com",
          Diff: false,
          ChangeRequest: null,
        },
      ],
    },
    {
      FieldName: "MasterID",
      Label: "Master ID",
      Records: [
        {
          Soid: "5f2cbf8ef85e4d7d54efea14",
          Value: "456892",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea35",
          Value: "456892",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea56",
          Value: "456892",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea77",
          Value: "456892",
          Diff: false,
          ChangeRequest: null,
        },
      ],
    },
    {
      FieldName: "BorrowerID",
      Label: "Borrower ID",
      Records: [
        {
          Soid: "5f2cbf8ef85e4d7d54efea14",
          Value: "3498999",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea35",
          Value: "3498999",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea56",
          Value: "3498999",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea77",
          Value: "3498999",
          Diff: false,
          ChangeRequest: null,
        },
      ],
    },
    {
      FieldName: "DepositorID",
      Label: "Depositor ID",
      Records: [
        {
          Soid: "5f2cbf8ef85e4d7d54efea14",
          Value: "4356699",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea35",
          Value: "4356699",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea56",
          Value: "4356699",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea77",
          Value: "4356699",
          Diff: false,
          ChangeRequest: null,
        },
      ],
    },
    {
      FieldName: "TIN",
      Label: "TIN",
      Records: [
        {
          Soid: "5f2cbf8ef85e4d7d54efea14",
          Value: "672134798",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea35",
          Value: "672134798",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea56",
          Value: "672134798",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea77",
          Value: "672134798",
          Diff: false,
          ChangeRequest: null,
        },
      ],
    },
    {
      FieldName: "SSN",
      Label: "SSN",
      Records: [
        {
          Soid: "5f2cbf8ef85e4d7d54efea14",
          Value: "",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea35",
          Value: "",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea56",
          Value: "",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea77",
          Value: "",
          Diff: false,
          ChangeRequest: null,
        },
      ],
    },
    {
      FieldName: "Account1",
      Label: "Account 1",
      Records: [
        {
          Soid: "5f2cbf8ef85e4d7d54efea14",
          Value: "4578115672",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea35",
          Value: "4578115672",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea56",
          Value: "4578115672",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea77",
          Value: "4578115672",
          Diff: false,
          ChangeRequest: null,
        },
      ],
    },
    {
      FieldName: "Account2",
      Label: "Account 2",
      Records: [
        {
          Soid: "5f2cbf8ef85e4d7d54efea14",
          Value: "6712367889",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea35",
          Value: "6712367889",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea56",
          Value: "6712367889",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea77",
          Value: "6712367889",
          Diff: false,
          ChangeRequest: null,
        },
      ],
    },
    {
      FieldName: "RelationshipManager1",
      Label: "Relationship Manager 1",
      Records: [
        {
          Soid: "5f2cbf8ef85e4d7d54efea14",
          Value: "Buffy Jones",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea35",
          Value: "Buffy Jones",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea56",
          Value: "Buffy Jones",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea77",
          Value: "Buffy Jones",
          Diff: false,
          ChangeRequest: null,
        },
      ],
    },
    {
      FieldName: "RelationshipManager2",
      Label: "RelationshipManager 2",
      Records: [
        {
          Soid: "5f2cbf8ef85e4d7d54efea14",
          Value: "",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea35",
          Value: "",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea56",
          Value: "",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea77",
          Value: "",
          Diff: false,
          ChangeRequest: null,
        },
      ],
    },
    {
      FieldName: "RelationshipManager3",
      Label: "RelationshipManager 3",
      Records: [
        {
          Soid: "5f2cbf8ef85e4d7d54efea14",
          Value: "",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea35",
          Value: "",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea56",
          Value: "",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea77",
          Value: "",
          Diff: false,
          ChangeRequest: null,
        },
      ],
    },
    {
      FieldName: "CostCenter",
      Label: "Cost Center",
      Records: [
        {
          Soid: "5f2cbf8ef85e4d7d54efea14",
          Value: "235",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea35",
          Value: "235",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea56",
          Value: "235",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea77",
          Value: "235",
          Diff: false,
          ChangeRequest: null,
        },
      ],
    },
    {
      FieldName: "PrimaryContact",
      Label: "Primary Contact",
      Records: [
        {
          Soid: "5f2cbf8ef85e4d7d54efea14",
          Value: "Kelsey Granderson",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea35",
          Value: "Kelsey Granderson",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea56",
          Value: "Kelsey Granderson",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea77",
          Value: "Kelsey Granderson",
          Diff: false,
          ChangeRequest: null,
        },
      ],
    },
    {
      FieldName: "EntityType",
      Label: "Entity Type",
      Records: [
        {
          Soid: "5f2cbf8ef85e4d7d54efea14",
          Value: "LLC",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea35",
          Value: "LLC",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea56",
          Value: "LLC",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea77",
          Value: "LLC",
          Diff: false,
          ChangeRequest: null,
        },
      ],
    },
    {
      FieldName: "NAICSCode1",
      Label: "NAICS Code",
      Records: [
        {
          Soid: "5f2cbf8ef85e4d7d54efea14",
          Value: "278562",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea35",
          Value: "278562",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea56",
          Value: "278562",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea77",
          Value: "278562",
          Diff: false,
          ChangeRequest: null,
        },
      ],
    },
    {
      FieldName: "StateOfOrganization",
      Label: "State Of Organization",
      Records: [
        {
          Soid: "5f2cbf8ef85e4d7d54efea14",
          Value: "California",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea35",
          Value: "California",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea56",
          Value: "California",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea77",
          Value: "California",
          Diff: false,
          ChangeRequest: null,
        },
      ],
    },
    {
      FieldName: "BorrowerRiskRating",
      Label: "Borrower Risk Rating",
      Records: [
        {
          Soid: "5f2cbf8ef85e4d7d54efea14",
          Value: "5",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea35",
          Value: "7",
          Diff: true,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea56",
          Value: "2",
          Diff: true,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea77",
          Value: "11",
          Diff: true,
          ChangeRequest: null,
        },
      ],
    },
    {
      FieldName: "GuarantorRiskRating",
      Label: "Guarantor Risk Rating",
      Records: [
        {
          Soid: "5f2cbf8ef85e4d7d54efea14",
          Value: "6",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea35",
          Value: "",
          Diff: true,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea56",
          Value: "6",
          Diff: false,
          ChangeRequest: null,
        },
        {
          Soid: "5f2cbf8ef85e4d7d54efea77",
          Value: "6",
          Diff: false,
          ChangeRequest: null,
        },
      ],
    },
  ],
}
