const mockData = [
    {
        _id: "1",
        loanName: "Test #1",
        loanType: "Student Loan",
        commitmentAmount: "$123,456,789",
        maturityDate: "2025-01-01",
        borrowerID: '12354',
        borrowerName: "Jill",
        Actions: "",
    },
    {
        _id: "2",
        loanName: "Test #2",
        loanType: "Mortgage Loan",
        commitmentAmount: "$900,000",
        maturityDate: "2028-09-09",
        borrowerID: '34444',
        borrowerName: "Barry",
        Actions: "",
    },
    {   
        _id: "3",
        loanName: "Test #3",
        loanType: "Auto Loan",
        commitmentAmount: "$456,000",
        maturityDate: "2030-03-28",
        borrowerID: '76573',
        borrowerName: "Jeff",
        Actions: "",
    },
    {
        _id: "4",
        loanName: "Test #4",
        loanType: "Personal Loan",
        commitmentAmount: "$989,000",
        maturityDate: "2024-11-11",
        borrowerID: '54367',
        borrowerName: "Risa",
        Actions: "",
    },
    {
        _id: "5",
        loanName: "Test #5",
        loanType: "Home Equity",
        commitmentAmount: "$1,080,000",
        maturityDate: "2035-01-01",
        borrowerID: '98345',
        borrowerName: "Mark",
        Actions: "",
    },
    {
        _id: "1",
        loanName: "Test #6 ",
        loanType: "Auto title Loan",
        commitmentAmount: "Jane Doe",
        maturityDate: "2025-12-12",
        borrowerID: '43254',
        borrowerName: "Bill",
        Actions: "",
    },
  
  ]

export default mockData