exports.BASEFIELDS= [
  "Warehouse",
  "PrimaryBorrowerName",
  "CoBorrowerName1",
  "CoBorrowerName2",
  "CoBorrowerName2",
  "CoBorrowerName3",
  "CoBorrowerName3",
  "GuarantorName1",
  "GuarantorName2",
  "GuarantorName3",
  "GuarantorName4",
  "GuarantorName5",
  "PrimaryBorrowerBID",
  "CoBorrowerBID1",
  "CoBorrowerBID2",
  "CoBorrowerBID3",
  "CoBorrowerBID4",
  "CoBorrowerBID5",
  "GuarantorBID1",
  "GuarantorBID2",
  "GuarantorBID3",
  "GuarantorBID4",
  "GuarantorBID5",
  "GuarantorType1",
  "PrimaryBorrowerTIN/SSN1",
  "Co-BorrowerTIN/SSN1",
  "Co-BorrowerTIN/SSN2",
  "Co-BorrowerTIN/SSN3",
  "Co-BorrowerTIN/SSN4",
  "Co-BorrowerTIN/SSN5",
  "LoanID",
  "LoanType",
  "OtherLoanType",
  "CommitmentAmount",
  "OutstandingAmount",
  "IsSublimit?",
  "MaturityTimeFrame",
  "MatiurityDate",
  "MaturityValue",
  "InterestRateType1",
  "InterestRateType2",
  "InterestRateType3",
  "InterestRateType4",
  "InterestRateType5",
  "InterestRate1",
  "InterestRate2",
  "InterestRate3",
  "InterestRate4",
  "InterestRate5",
  "InterestRateCeiling",
  "InterestRateFloor",
  "FeeType1",
  "FeeType2",
  "FeeType3",
  "FeeType4",
  "FeeType5",
  "FeeAmount1",
  "FeeAmount2",
  "FeeAmount3",
  "FeeAmount4",
  "FeeAmount5",
  "Purpose",
  "DetailedPurpose",
  "Syndication",
  "LienPriority",
  "CollateralType",
  "RiskRating",
  "OriginalFacilityID",
  "OriginationDate",
  "LineReportedOnFrY-9C",
  "CostCenter",
  "Division",
  "LineOfBusiness",
  "CumalitiveChargeOffs",
  "ASC310-10",
  "ASC310-30",
  "NumberofDaysPrincialorInterestPastDue",
  "Non-AccrualDays",
  "IDOfPrimaryObligorForRepayment",
  "DateOfFinancials",
  "DateOfLast Audit",
  "NetSalesCurrent",
  "NetSalesPrior Year",
  "OperatingIncome",
  "DepreciationAndAmortization",
  "InterestExpense",
  "NetIncomeCurrent",
  "NetIncomePrioryYear",
  "CashAndMarketableSecurities",
  "AccountsReceivableCurrent",
  "AccountsReceivablePrior Year",
  "InventoryCurrent",
  "InventoryPriorYear",
  "CurrentAssetsCurrent",
  "CurrentAssetsPriorYear",
  "TangibleAssets",
  "FixedAssets",
  "TotalAssetsCurrent",
  "TotalAssetsPrior Year",
  "AccountsPayableCurrent",
  "AccountsPayablePriorYear",
  "ShortTermDebt",
  "CurrentMaturitiesOfLongTermDebt",
  "CurrentLiabilitiesCurrent",
  "CurrentLiabilitiesPriorYear",
  "LongTermDebt",
  "MinorityInterest",
  "TotalLiabilities",
  "RetainedEarnings",
  "CapitalExpenditures",
  "SpecialPurpose Entity Flag",
  "FairValueAdjustmentCommittedExposure",
  "FairValueAdjustmentDrawn",
  "LowerOfCostOrMarketFlag",
  "SNCInternalCreditID",
  "ProbabilityOfDefault",
  "LossGivenDefault",
  "ExposureAtDefault",
  "RenewalDate",
  "CreditFacilityCurrency",
  "EstimatedValue(Collateral)",
  "PrepaymentPenalty",
  "PSRIndustryCode",
  "ShareOfTotalCommitment",
  "LeveragedLoan",
  "DispositionFlag",
  "DispostionScheduleShift",
  "SyndicationType",
  "TargetHold",
  "FedCodes",
  "CCARLiens",
  "PropertyType",
  "LoanPuproseRELOAN",
  "LowerOfCostOrMarketFlag__1",
  "ISO4127CurrencyCodes",
  "CurrentValueBasis",
  "PrepaymentPenaltyFlag",
  "LeveragedLoanFlag",
  "TroubledDebtRestructuring",
  "AcquiredLoan",
  "Recourse",
  "ParicipationFlag",
  "IndustryCodeType",
  "CreditFacilityType",
  "CreditFacilityPurpose",
  "LineReportedOnFR-Y-9C",
  "interestIncomeTaxStatus",
  "SyndicatedLoanFlag",
]

exports.BASEFIELDS_NAME= [
  "Warehouse",
  "Primary Borrower Name",
  "Co-Borrower Name 1",
  "Co Borrower Name 2",
  "Co-Borrower Name 2",
  "Co Borrower Name 3",
  "Co-Borrower Name 3",
  "Guarantor Name 1",
  "Guarantor Name 2",
  "Guarantor Name 3",
  "Guarantor Name 4",
  "Guarantor Name 5",
  "Primary Borrower BID",
  "Co-Borrower BID 1",
  "Co Borrower BID 2",
  "Co-Borrower BID 3",
  "Co Borrower BID 4",
  "Co-Borrower BID 5",
  "Guarantor BID 1",
  "Guarantor BID 2",
  "Guarantor BID 3",
  "Guarantor BID 4",
  "Guarantor BID 5",
  "Guarantor Type 1",
  "Primary Borrower TIN/SSN 1",
  "Co-Borrower TIN/SSN 1",
  "Co-Borrower TIN/SSN 2",
  "Co-Borrower TIN/SSN 3",
  "Co-Borrower TIN/SSN 4",
  "Co-Borrower TIN/SSN 5",
  "Loan ID",
  "Loan Type",
  "Other Loan Type",
  "Commitment Amount",
  "Outstanding Amount",
  "Is Sublimit?",
  "Maturity Time Frame",
  "Matiurity Date",
  "Maturity Value",
  "Interest Rate Type 1",
  "Interest Rate Type 2",
  "Interest Rate Type 3",
  "Interest Rate Type 4",
  "Interest Rate Type 5",
  "Interest Rate 1",
  "Interest Rate 2",
  "Interest Rate 3",
  "Interest Rate 4",
  "Interest Rate 5",
  "Interest Rate Ceiling",
  "Interest Rate Floor",
  "Fee Type 1",
  "Fee Type 2",
  "Fee Type 3",
  "Fee Type 4",
  "Fee Type 5",
  "Fee Amount 1",
  "Fee Amount 2",
  "Fee Amount 3",
  "Fee Amount 4",
  "Fee Amount 5",
  "Purpose",
  "Detailed Purpose",
  "Syndication",
  "Lien Priority",
  "Collateral Type",
  "Risk Rating",
  "Original Facility ID",
  "Origination Date",
  "Line Reported on Fr Y-9C",
  "Cost Center",
  "Division",
  "Line of Business",
  "Cumalitive ChargeOffs",
  "ASC 310-10",
  "AS C310-30",
  "# of Days Princial or Interest Past Due",
  "non-Accrual Days",
  "ID of Primary Obligor for Repayment",
  "Date of Financials",
  "Date of Last Audit",
  "Net Sales Current",
  "Net Sales Prior Year",
  "Operating Income",
  "Depreciation & Amortization",
  "Interest Expense",
  "Net Income Current",
  "Net Income Priory Year",
  "Cash & Marketable Securities",
  "Accounts Receivable (A/R) Current",
  "Accounts Receivable (A/R) Prior Year",
  "Inventory Current",
  "Inventory Prior Year",
  "Current Assets Current",
  "Current Assets Prior Year",
  "Tangible Assets",
  "Fixed Assets",
  "Total Assets (TA) Current",
  "Total Assets (TA) Prior Year",
  "Accounts Payable (A/P) Current",
  "Accounts Payable (A/P) Prior Year",
  "Short Term Debt",
  "Current Maturities of Long Term Debt",
  "Current Liabilities Current",
  "Current Liabilities Prior Year",
  "Long Term Debt",
  "Minority Interest",
  "Total Liabilities",
  "Retained Earnings",
  "Capital Expenditures",
  "Special Purpose Entity Flag",
  "Fair Value Adjustment Committed Exposure",
  "Fair Value Adjustment Drawn",
  "Lower of Cost or Market Flag",
  "SNC Internal Credit ID",
  "Probability of Default (PD)",
  "Loss Given Default (LGD)",
  "Exposure At Default (EAD)",
  "Renewal Date",
  "Credit Facility Currency",
  "Estimated Value (Collateral)",
  "Prepayment Penalty",
  "PSR Industry Code",
  "Share of Total Commitment",
  "Leveraged Loan",
  "Disposition Flag",
  "Dispostion Schedule Shift",
  "Syndication Type",
  "Target Hold",
  "Fed Codes",
  "CCAR Liens",
  "Property Type",
  "Loan Puprose RE-LOAN",
  "Lower of Cost or Market Flag__1",
  "ISO 4127 Currency Codes",
  "Current Value Basis",
  "Prepayment Penalty Flag",
  "Leveraged Loan Flag",
  "Troubled Debt Restructuring",
  "Acquired Loan",
  "Recourse",
  "Paricipation Flag",
  "Industry Code Type",
  "Credit Facility Type",
  "Credit Facility Purpose",
  "Line Reported on FR-Y-9C",
  "interest Income Tax Status",
  "Syndicated Loan Flag",
]
exports.TableHeaders = [
  {
    "Label": "Field Name",
    "Accessor": "FieldName"
  },
  {
    "Label": "FIS",
    "Accessor": "FIS"
  },
  {
    "Label": "Temenos",
    "Accessor": "Temenos"
  },
  {
    "Label": "Salesforce",
    "Accessor": "Salesforce"
  },
  {
    "Label": "DataWarehouse",
    "Accessor": "DataWarehouse"
  }
]