exports.BASEFIELDS= [
  'userId',
  'RelationshipName',
  'BorrowerName',
  'DepositorName',
  'HQStreetAddress',
  'HQCity',
  'HQState',
  'HQPostalCode',
  'HQCountry',
  'MailingAddress',
  'MailingCity',
  'MailingState',
  'MailingPostalCode',
  'MailingAddressCountry',
  'PhoneNumberOne',
  'PhoneNumberTwo',
  'PhoneNumberThree',
  'PhoneTypeOne',
  'PhoneTypeTwo',
  'PhoneTypeThree',
  'EmailOne',
  'EmailTwo',
  'EmailThree',
  'MasterID',
  'BorrowerID',
  'DepositorID',
  'AccountOne',
  'AccountTwo',
  'AccountThree',
  'TIN',
  'EntityType',
  'CostCenter',
  'NACISCode',
  'RelationshipManager',
  'PrimaryContact',
  'BorrowerRiskRating',
  'GuarantorRiskRating',
]

exports.BASEFIELDS_NAME= [
  'userId',
  'Relationship Name',
  'Borrower Name',
  'Depositor Name',
  'HQ Street Address',
  'HQ City',
  'HQ State',
  'HQ PostalCode',
  'HQ Country',
  'Mailing Address',
  'Mailing City',
  'Mailing State',
  'Mailing Postal Code',
  'Mailing Address Country',
  'Phone Number One',
  'Phone Number Two',
  'Phone Number Three',
  'Phone Type One',
  'Phone Type Two',
  'Phone Type Three',
  'Email One',
  'Email Two',
  'Email Three',
  'Master ID',
  'Borrower ID',
  'Depositor ID',
  'Account One',
  'Account Two',
  'Account Three',
  'TIN',
  'Entity Type',
  'Cost Center',
  'NACIS Code',
  'Relationship Manager',
  'Primary Contact',
  'Borrower RiskRating',
  'Guarantor RiskRating',
]
exports.TableHeaders = [
  {
    "Label": "Field Name",
    "Accessor": "FieldName"
  },
  {
    "Label": "FIS",
    "Accessor": "FIS"
  },
  {
    "Label": "Temenos",
    "Accessor": "Temenos"
  },
  {
    "Label": "Salesforce",
    "Accessor": "Salesforce"
  },
  {
    "Label": "DataWarehouse",
    "Accessor": "DataWarehouse"
  }
]